server:
  port: 8081
spring:
  jpa:
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.159.131:3306/db_stock?useSSL=false&serverTimezone=UTC
    username: root
    password: root
seata:
  enabled: true
  application-id: stock-service
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091